{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-conf
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden.name" . }}
    helm.sh/chart: {{ include "vaultwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DOMAIN: http{{ if .Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.domain }}
  {{- range $key, $val := .Values.vaultwarden }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end}}
  {{ if .Values.storage.enabled -}}
  DATA_FOLDER: {{ .Values.storage.path }}
  {{ end }}
