{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vaultwarden.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $newNetworkingAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $webSocketEnabled := .Values.vaultwarden.websocket_enabled }}
{{- if $newNetworkingAPI }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden.name" . }}
    helm.sh/chart: {{ include "vaultwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ $fullName }}-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: '/'
            pathType: ImplementationSpecific
            backend:
              {{- if $newNetworkingAPI }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
              {{- end }}
          {{- end }}
          {{- if $webSocketEnabled }}
          - path: /notifications/hub
            pathType: ImplementationSpecific
            backend:
              {{- if $newNetworkingAPI }}
              service:
                name: {{ $fullName }}
                port:
                  name: ws
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: ws
              {{- end }}
          - path: /notifications/hub/negotiate
            pathType: ImplementationSpecific
            backend:
              {{- if $newNetworkingAPI }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
              {{- end }}
          {{- end }}
{{- end }}
