apiVersion: v1
appVersion: 1.33.2
description: A Helm chart to install vaultwarden
name: vaultwarden
version: 1.33.2
home: https://github.com/c0deaddict/helm-vaultwarden
maintainers:
- name: Skeen
  email: sovende@gmail.com
- name: Jos van Bakel
  email: jos@codeaddict.org
