# Override all names
nameOverride: ""
fullnameOverride: ""

# Vaultwarden configuration.
# The below values are used to construct a config map, which will be provided
# to the vaultwarden container on start up.
# For details about the options, see: https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview
vaultwarden:
  # # Allow registration of new users
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Disable-registration-of-new-users
  # signups_allowed: true

  # # Allow current users invite new users even if registrations are otherwise disabled.
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Disable-invitations
  # invitations_allowed: true

  # # Websocket support for notifications
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications
  websocket_enabled: true
  websocket_port: 3012

  # # Needed for U2F authentification
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-U2F-%28and-FIDO2-WebAuthn%29-authentication
  # # Configuration of YubiKey OTP
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Yubikey-OTP-authentication
  # yubico_client_id: YUBICO_CLIENT_ID
  # yubico_secret_key: YUBICO_SECRET_KEY

  # # API request size limits
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Changing-the-API-request-size-limit
  # rocket_limits: "{json=10485760}"

  # # Number of workers to spin up for the service
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Changing-the-number-of-workers
  # rocket_workers: 10

  # # SMTP settings, for sending out emails
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/SMTP-Configuration
  # smtp_host: smtp.domain.tldy
  # smtp_from: bitwarden@domain.tld
  # smtp_port: 587
  # smtp_security: starttls
  # smtp_username: username
  # smtp_password: password

  # Show password hint instead of sending it via email
  # See: https://github.com/dani-garcia/vaultwarden/wiki/Password-hint-display
  show_password_hint: false

  # Enable Vault interface, when disabled, only API is served
  # See: https://github.com/dani-garcia/vaultwarden/wiki/Disabling-or-overriding-the-Vault-interface-hosting
  web_vault_enabled: true

  # # Logging to a specific file
  # # See: https://github.com/dani-garcia/vaultwarden/wiki/Logging
  # log_file=/data/vaultwarden.log

  # Port to serve http requests on. Define it accordingly to the service's target_port
  rocket_port: 8080

  # NOTE: DOMAIN cannot be set here, as it is derived from the ingress configuration below.
  # NOTE: DATA_FOLDER cannot be set here, as it is derived from the storage.path below.
  # TODO: Support DATABASE_URL, ATTACHMENTS_FOLDER, ICON_CACHE_FOLDER


deployment:
  # Image used for the deployment
  # See: https://www.github.com/dani-garcia/vaultwarden
  image:
    repository: vaultwarden/server
    tag: 1.25.0
    pullPolicy: IfNotPresent
  # Resources, etc, for the deployment pod
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Passwords and sensitive data can also be provided via secrets. This can be used for ADMIN_TOKEN and SMTP_PASSWORD.
  # Just provide the names of your secret resources that are already deployed to your namespace.
  secrets: []

securityContext:
  enabled: false
  runAsNonRoot: true
  fsGroup: 1000
  runAsUser: 1000

# Should not be changed
service:
  type: ClusterIP
  port: 80
  target_port: 8080


# Settings regarding persistent storage
# TODO: Support DATABASE_URL + ATTACHMENTS_FOLDER + ICON_CACHE_FOLDER
# See: https://github.com/dani-garcia/vaultwarden/wiki/Changing-persistent-data-location
storage:
  # Whether storing persistent data is enabled or not
  enabled: true
  # Where to store persistent data
  path: "/bw-data"
  # The maximum size of the persisted data
  size: 100Mi


# Settings regarding persistent backup storage
backup:
  # Whether backup is enabled or not
  enabled: false
  # Where to store the backup data
  path: "/bw-backup"
  # The maximum size of the persisted backup data
  size: 100Mi

  # Cron schedule for the backup job (currently at 3:00 every night)
  schedule: "* 3 * * *"

  # Name the backup backup.sqlite3[TIMESTAMP] instead of backup.sqlite3
  timestamp: false
  # Create a file containing the timestamp of the backup
  timestamp_file: "/bw-backup/timestamp"

  # Image used for backup run
  # See: https://github.com/Skeen/bitwarden_rs_backup
  image:
    repository: skeen/bitwarden_rs_backup
    tag: latest
    pullPolicy: Always

  # Resources, etc, for the backup pod(s)
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


# Ingress configuration
ingress:
  enabled: true
  domain: bw.domain.tld
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  tls: true
